force-app/main/default/objects/Card_Set__mdt/Card_Set__mdt.object-meta.xml
<CustomObject>
    <label>Card Set</label>
    <pluralLabel>Card Sets</pluralLabel>
</CustomObject>

force-app/main/default/objects/Content_Backlog_Item__c/Content_Backlog_Item__c.object-meta.xml
<CustomObject>
    <label>Content Backlog Item</label>
    <nameField>
        <displayFormat>Backlog-{0000}</displayFormat>
        <label>Content Backlog Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Content_Backlog_Item__c/fields/Topic__c.field-meta.xml
<CustomField>
    <fullName>Topic__c</fullName>
    <label>Topic</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/Config__c.field-meta.xml
<CustomField>
    <fullName>Config__c</fullName>
    <label>Config</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Game_Key__c.field-meta.xml
<CustomField>
    <fullName>Game_Key__c</fullName>
    <formula>MID(Id, 11, 5)</formula>
    <label>Game Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/PlanningPokerTest.cls
@isTest
public class PlanningPokerTest {

    @TestSetup
    static void makeData(){
        List<Game__c> games = new List<Game__c>();
        
        Game__c g = new Game__c();
        g.Phase__c = 'In Progress';
        g.Name = 'Test 1';
        g.Config__c = null;
        games.add(g);

        g = new Game__c();
        g.Phase__c = 'In Progress';
        g.Name = 'Test 1';
        g.Config__c = '{"listViewId":"0000000000"}';
        games.add(g);

        g = new Game__c();
        g.Phase__c = 'Completed';
        g.Name = 'Test 1';
        g.Config__c = '{"listViewId":"0000000000"}';
        games.add(g);

        insert games;

        List<Content_Backlog_Item__c> backlogItems = new List<Content_Backlog_Item__c>();

        Content_Backlog_Item__c bi = new Content_Backlog_Item__c();
        bi.Topic__c = 'b1';
        bi.Notes__c = 'n1';
        backlogItems.add(bi);

        bi = new Content_Backlog_Item__c();
        bi.Topic__c = 'b2';
        bi.Notes__c = 'n2';
        backlogItems.add(bi);

        insert backlogItems;

    }

    @IsTest
    static void checkGameSettings(){
        Test.startTest();

        List<Card_Set__mdt> cardSets = PlanningPokerCtrl.getAvailableCardSets();
        System.assertEquals(2, cardSets.size());

        List<String> customObjects = PlanningPokerCtrl.getCustomObjects();
        System.assert(customObjects.contains('Game__c'));

        List<ListView> views = PlanningPokerCtrl.getListViewsOfObject('Game__c');
        System.assert(views.size() > 0);

        Test.stopTest();
    }

    @IsTest
    static void checkGames(){
        Game__c existingGame = [select Id, Game_Key__c from Game__c limit 1];

        Test.startTest();
        List<Game__c> games = PlanningPokerCtrl.getValidGames();
        System.assertEquals(1, games.size());

        Game__c game = PlanningPokerCtrl.getGameByGameKey('000000');
        system.assertEquals(null, game);

        game = PlanningPokerCtrl.getGameByGameKey(existingGame.Game_Key__c);
        system.assertEquals(existingGame.Id, game.Id);

        Test.stopTest();
        
    }
}