force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Players Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Player_Response__c/Player_Response__c.object-meta.xml
<CustomObject>
    <label>Player Response</label>
    <nameField>
        <displayFormat>PlayerResponse-{000}</displayFormat>
        <label>Player Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Player Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Player_Response__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Player Responses</relationshipLabel>
    <relationshipName>Player_Responses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Player_Response__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Player__c</referenceTo>
    <relationshipLabel>Player Responses</relationshipLabel>
    <relationshipName>Player_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Player_Response__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Player_Response__c/fields/Story_ID__c.field-meta.xml
<CustomField>
    <fullName>Story_ID__c</fullName>
    <label>Story ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PlanningPokerPostInstallScript.cls
global class PlanningPokerPostInstallScript implements InstallHandler {
    global void onInstall(InstallContext context) {
        if (context.previousVersion() == null) {
            String namespace = PlanningPokerCtrl.getNameSpace();
            insertPushTopics(namespace);
        }
    }

    public static void insertPushTopics(String namespace) {
        if (namespace != null && namespace != '' && !namespace.endsWith('__')) {
            namespace = namespace + '__';
        }

        List<PushTopic> pushTopics = new List<PushTopic>();

        PushTopic pushTopic = new PushTopic();
        pushTopic.Name = 'GamePlayers';
        pushTopic.Query =
            'SELECT Id, Name, ' +
            namespace +
            'Game__c from ' +
            namespace +
            'Player__c';
        pushTopic.ApiVersion = 49.0;
        pushTopic.NotifyForOperationCreate = true;
        pushTopic.NotifyForOperationUpdate = false;
        pushTopic.NotifyForOperationUndelete = false;
        pushTopic.NotifyForOperationDelete = true;
        pushTopic.NotifyForFields = 'Referenced';
        pushTopics.add(pushTopic);

        pushTopic = new PushTopic();
        pushTopic.Name = 'PlayerResponses';
        pushTopic.Query =
            'SELECT Id, ' +
            namespace +
            'Story_ID__c, ' +
            namespace +
            'Game__c, ' +
            namespace +
            'Response__c, ' +
            namespace +
            'Player__c from ' +
            namespace +
            'Player_Response__c';
        pushTopic.ApiVersion = 49.0;
        pushTopic.NotifyForOperationCreate = true;
        pushTopic.NotifyForOperationUpdate = true;
        pushTopic.NotifyForOperationUndelete = false;
        pushTopic.NotifyForOperationDelete = true;
        pushTopic.NotifyForFields = 'Referenced';
        pushTopics.add(pushTopic);

        insert pushTopics;
    }
}