force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/Current_Story_ID__c.field-meta.xml
<CustomField>
    <fullName>Current_Story_ID__c</fullName>
    <label>Current Story ID</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Game_Key__c.field-meta.xml
<CustomField>
    <fullName>Game_Key__c</fullName>
    <formula>MID(Id, 11, 5)</formula>
    <label>Game Key</label>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Game__c/fields/Question_Offset__c.field-meta.xml
<CustomField>
    <fullName>Question_Offset__c</fullName>
    <label>Question Offset</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
    <defaultValue>0</defaultValue>
</CustomField>

force-app/main/default/objects/Game__c/fields/Timer_Timestamp__c.field-meta.xml
<CustomField>
    <fullName>Timer_Timestamp__c</fullName>
    <label>Timer Timestamp</label>
    <length>18</length>
    <type>Text</type>
</CustomField>

force-app/test/default/classes/PlanningPokerGamePlayTest.cls
@isTest
public class PlanningPokerGamePlayTest {
    @TestSetup
    static void createData() {
        PlanningPokerTestUtil.createTestData();
    }

    @IsTest
    static void checkGameQueries() {
        Game__c existingGame = [SELECT Id, Game_Key__c FROM Game__c LIMIT 1];

        Test.startTest();
        List<Game__c> games = PlanningPokerCtrl.getValidGames();
        System.assertEquals(1, games.size());

        Game__c game = PlanningPokerCtrl.getGameByGameKey('000000');
        system.assertEquals(null, game);

        game = PlanningPokerCtrl.getGameByGameKey(existingGame.Game_Key__c);
        system.assertEquals(existingGame.Id, game.Id);

        Test.stopTest();
    }

    @isTest
    static void checkIfGameStoryIsUpdated() {
        Game__c g = [
            SELECT
                Id,
                Current_Story_ID__c,
                Timer_Timestamp__c,
                Question_Offset__c
            FROM Game__c
            WHERE Name = 'Test 2'
        ];

        final String STORY_ID = '000000';
        final Integer OFFSET = 2;

        Test.startTest();
        PlanningPokerCtrl.updateGameCurrentStory(g.Id, STORY_ID, 2);
        Game__c updatedGame = [
            SELECT
                Id,
                Current_Story_ID__c,
                Timer_Timestamp__c,
                Question_Offset__c
            FROM Game__c
            WHERE Name = 'Test 2'
        ];

        system.assertEquals(STORY_ID, updatedGame.Current_Story_ID__c);
        system.assertEquals(OFFSET, updatedGame.Question_Offset__c);
        system.assertNotEquals(
            g.Timer_Timestamp__c,
            updatedGame.Timer_Timestamp__c
        );

        Test.stopTest();
    }

    @isTest
    static void checkIfGamePhaseIsUpdated() {
        Game__c g = [SELECT Id, Phase__c FROM Game__c WHERE Name = 'Test 4'];

        Test.startTest();
        system.assertEquals('Not Started', g.Phase__c);
        PlanningPokerCtrl.changeGamePhase(g.Id, 'Not Started');

        g = [SELECT Id, Phase__c FROM Game__c WHERE Name = 'Test 4'];
        system.assertEquals('Registration', g.Phase__c);
        PlanningPokerCtrl.changeGamePhase(g.Id, 'Registration');

        g = [SELECT Id, Phase__c FROM Game__c WHERE Name = 'Test 4'];
        system.assertEquals('In Progress', g.Phase__c);
        PlanningPokerCtrl.changeGamePhase(g.Id, 'In Progress');

        g = [SELECT Id, Phase__c FROM Game__c WHERE Name = 'Test 4'];
        system.assertEquals('Completed', g.Phase__c);

        Test.stopTest();
    }
}