force-app/main/default/objects/Backlog_Item__c/Backlog_Item__c.object-meta.xml
<CustomObject>
    <label>Backlog Item</label>
    <nameField>
        <displayFormat>Backlog-{0000}</displayFormat>
        <label>Backlog Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Backlog_Item__c/fields/Notes__c.field-meta.xml
<CustomField>
    <fullName>Notes__c</fullName>
    <label>Notes</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Backlog_Item__c/fields/User_Story__c.field-meta.xml
<CustomField>
    <fullName>User_Story__c</fullName>
    <label>User Story</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Card_Set__mdt/Card_Set__mdt.object-meta.xml
<CustomObject>
    <label>Card Set</label>
    <pluralLabel>Card Sets</pluralLabel>
</CustomObject>

force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/fields/Config__c.field-meta.xml
<CustomField>
    <fullName>Config__c</fullName>
    <label>Config</label>
    <length>32768</length>
    <type>LongTextArea</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Host_can_vote__c.field-meta.xml
<CustomField>
    <fullName>Host_can_vote__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Host can vote</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Phase__c.field-meta.xml
<CustomField>
    <fullName>Phase__c</fullName>
    <label>Phase</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Not Started</fullName>
                <default>true</default>
                <label>Not Started</label>
            </value>
            <value>
                <fullName>Registration</fullName>
            </value>
            <value>
                <fullName>In Progress</fullName>
            </value>
            <value>
                <fullName>Completed</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Game__c/fields/Show_Timer__c.field-meta.xml
<CustomField>
    <fullName>Show_Timer__c</fullName>
    <defaultValue>false</defaultValue>
    <label>Show Timer</label>
    <type>Checkbox</type>
</CustomField>

force-app/main/default/objects/Game__c/fields/Timer_Duration__c.field-meta.xml
<CustomField>
    <fullName>Timer_Duration__c</fullName>
    <label>Timer Duration (in seconds)</label>
    <precision>3</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Players Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/test/default/classes/PlanningPokerTestUtil.cls
public class PlanningPokerTestUtil {
    public static String namespace = PlanningPokerCtrl.getNameSpace(true);

    public static void createTestData() {
        List<Game__c> games = new List<Game__c>();

        Card_Set__mdt cs = [
            SELECT Id
            FROM Card_Set__mdt
            WHERE Label = 'Fibonacci'
        ];

        Game__c g = new Game__c();
        g.Phase__c = 'In Progress';
        g.Name = 'Test 1';
        g.Config__c = null;
        games.add(g);

        g = new Game__c();
        g.Phase__c = 'In Progress';
        g.Name = 'Test 2';
        g.Show_Timer__c = true;
        g.Timer_Duration__c = 20;
        g.Config__c =
            '{"cardSet":"' +
            cs.Id +
            '","object":"Backlog_Item__c","name":"User_Story__c","description":"Notes__c","consensus":"Consensus__c","listView":"00B0p000001XhUQEA0"}';
        games.add(g);

        g = new Game__c();
        g.Phase__c = 'Completed';
        g.Name = 'Test 3';
        g.Config__c = '{"listViewId":"00B0p000001XhUQEA0"}';
        games.add(g);

        g = new Game__c();
        g.Name = 'Test 4';
        g.Host_can_vote__c = true;
        g.Config__c =
            '{"cardSet":"' +
            cs.Id +
            '","object":"Backlog_Item__c","name":"User_Story__c","description":"Notes__c","consensus":"Consensus__c","listView":"00B0p000001XhUQEA0"}';
        games.add(g);

        insert games;

        List<Backlog_Item__c> backlogItems = new List<Backlog_Item__c>();

        Backlog_Item__c bi = new Backlog_Item__c();
        bi.User_Story__c = 'b1';
        bi.Notes__c = 'n1';
        backlogItems.add(bi);

        bi = new Backlog_Item__c();
        bi.User_Story__c = 'b2';
        bi.Notes__c = 'n2';
        backlogItems.add(bi);

        insert backlogItems;

        List<Player__c> players = new List<Player__c>();
        Player__c p = new Player__c();
        p.Name = 'player1';
        p.Game__c = games[1].Id;
        players.add(p);

        p = new Player__c();
        p.Name = 'player2';
        p.Game__c = games[1].Id;
        players.add(p);

        p = new Player__c();
        p.Name = UserInfo.getName();
        p.Game__c = games[1].Id;
        players.add(p);

        p = new Player__c();
        p.Name = 'player3';
        p.Game__c = games[0].Id;
        players.add(p);

        p = new Player__c();
        p.Name = UserInfo.getName();
        p.Game__c = games[0].Id;
        players.add(p);

        insert players;
    }

    public static PlanningPokerRest.PlanningPokerServicesResponse deserializeValues(
        String response
    ) {
        PlanningPokerRest.PlanningPokerServicesResponse ppr = new PlanningPokerRest.PlanningPokerServicesResponse();
        Map<String, Object> params = (Map<String, Object>) JSON.deserializeUntyped(
            response
        );
        ppr.isSuccess = (Boolean) params.get('isSuccess');
        ppr.errorMsg = (String) params.get('errorMsg');
        ppr.data = params.get('data');
        return ppr;
    }
}