force-app/main/default/objects/Content_Backlog_Item__c/Content_Backlog_Item__c.object-meta.xml
<CustomObject>
    <label>Content Backlog Item</label>
    <nameField>
        <displayFormat>Backlog-{0000}</displayFormat>
        <label>Content Backlog Item ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Content Backlog Items</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Game__c/Game__c.object-meta.xml
<CustomObject>
    <label>Game</label>
    <nameField>
        <label>Game Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Games</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/Player__c.object-meta.xml
<CustomObject>
    <label>Player</label>
    <nameField>
        <label>Players Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Players</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Player__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Players</relationshipLabel>
    <relationshipName>Players</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Player_Response__c/Player_Response__c.object-meta.xml
<CustomObject>
    <label>Player Response</label>
    <nameField>
        <displayFormat>PlayerResponse-{000}</displayFormat>
        <label>Player Response ID</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Player Responses</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/objects/Player_Response__c/fields/Game__c.field-meta.xml
<CustomField>
    <fullName>Game__c</fullName>
    <label>Game</label>
    <referenceTo>Game__c</referenceTo>
    <relationshipLabel>Player Responses</relationshipLabel>
    <relationshipName>Player_Responses</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Player_Response__c/fields/Player__c.field-meta.xml
<CustomField>
    <fullName>Player__c</fullName>
    <label>Player</label>
    <referenceTo>Player__c</referenceTo>
    <relationshipLabel>Player Responses</relationshipLabel>
    <relationshipName>Player_Responses</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

force-app/main/default/objects/Player_Response__c/fields/Response__c.field-meta.xml
<CustomField>
    <fullName>Response__c</fullName>
    <label>Response</label>
    <length>255</length>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Player_Response__c/fields/Story_ID__c.field-meta.xml
<CustomField>
    <fullName>Story_ID__c</fullName>
    <label>Story ID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/test/default/classes/PlanningPokerPlayerResponseTest.cls
@isTest
public class PlanningPokerPlayerResponseTest {
    @TestSetup
    static void createData() {
        PlanningPokerTestUtil.createTestData();
    }

    @isTest
    static void checkVoteCapture() {
        Game__c game = [SELECT Id FROM Game__c WHERE Name = 'Test 2'];
        Player__c player = [
            SELECT Id
            FROM Player__c
            WHERE Game__c = :game.Id
            LIMIT 1
        ];
        Content_Backlog_Item__c cbi = [
            SELECT Id
            FROM Content_Backlog_Item__c
            LIMIT 1
        ];

        List<Player_Response__c> responses = [
            SELECT Id
            FROM Player_Response__c
            WHERE
                Game__c = :game.Id
                AND Player__c = :player.Id
                AND Story_ID__c = :cbi.Id
        ];
        system.assertEquals(0, responses.size());

        Test.startTest();
        PlanningPokerCtrl.captureVote(cbi.Id, '0', player.Id, game.Id);

        responses = [
            SELECT Id, Response__c
            FROM Player_Response__c
            WHERE
                Game__c = :game.Id
                AND Player__c = :player.Id
                AND Story_ID__c = :cbi.Id
        ];
        system.assertEquals(1, responses.size());
        system.assertEquals('0', responses[0].Response__c);

        //Duplicate Vote
        PlanningPokerCtrl.captureVote(cbi.Id, '2', player.Id, game.Id);

        responses = [
            SELECT Id, Response__c
            FROM Player_Response__c
            WHERE
                Game__c = :game.Id
                AND Player__c = :player.Id
                AND Story_ID__c = :cbi.Id
        ];
        system.assertEquals(1, responses.size());
        system.assertEquals('2', responses[0].Response__c);

        Test.stopTest();
    }

    @isTest
    static void getExistingVotes() {
        Game__c game = [SELECT Id FROM Game__c WHERE Name = 'Test 4'];

        Player__c player = new Player__c();
        player.Name = 'Test Name';
        player.Game__c = game.Id;
        insert player;

        Content_Backlog_Item__c cbi = [
            SELECT Id
            FROM Content_Backlog_Item__c
            LIMIT 1
        ];
        PlanningPokerCtrl.captureVote(cbi.Id, '2', player.Id, game.Id);

        Test.startTest();
        List<PlanningPokerCtrl.PlayerResponse> responses = PlanningPokerCtrl.getPlayerResponses(
            game.Id,
            cbi.Id
        );
        system.assertEquals(1, responses.size());
        system.assertEquals(player.Id, responses[0].player.Id);
        system.assertEquals('2', responses[0].response);
        system.assertEquals('2', responses[0].pokerCard.name);
        Test.stopTest();
    }
}