force-app/main/default/objects/Game_State_Change__e/Game_State_Change__e.object-meta.xml
<CustomObject>
    <label>Game State Change</label>
    <pluralLabel>Game State Changes</pluralLabel>
</CustomObject>

force-app/main/default/objects/Game_State_Change__e/fields/Data__c.field-meta.xml
<CustomField>
    <fullName>Data__c</fullName>
    <label>Data</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Game_State_Change__e/fields/GameID__c.field-meta.xml
<CustomField>
    <fullName>GameID__c</fullName>
    <label>GameID</label>
    <length>18</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/objects/Game_State_Change__e/fields/Type__c.field-meta.xml
<CustomField>
    <fullName>Type__c</fullName>
    <label>Type</label>
    <length>20</length>
    <required>true</required>
    <type>Text</type>
</CustomField>

force-app/main/default/classes/PlanningPokerEventUtil.cls
public with sharing class PlanningPokerEventUtil {
    
    public static void fireStoryChangeEvent(String gameId, String storyId){
        Game_State_Change__e stateChangeEvent = new Game_State_Change__e();
        stateChangeEvent.GameID__c = gameId;
        stateChangeEvent.Type__c = 'StoryChange';
        stateChangeEvent.Data__c = storyId;
        Eventbus.publish(stateChangeEvent);
    }

    public static void fireGamePhaseChangeEvent(String gameId, String nextPhase){
        Game_State_Change__e stateChangeEvent = new Game_State_Change__e();
        stateChangeEvent.GameID__c = gameId;
        stateChangeEvent.Type__c = 'GamePhaseChange';
        stateChangeEvent.Data__c = nextPhase;
        Eventbus.publish(stateChangeEvent);
    }

    public static void fireFlipCardsEvent(String gameId, String flipped){
        Game_State_Change__e stateChangeEvent = new Game_State_Change__e();
        stateChangeEvent.GameID__c = gameId;
        stateChangeEvent.Type__c = 'CardFlip';
        stateChangeEvent.Data__c = flipped;
        Eventbus.publish(stateChangeEvent);
    }

    public static void fireResetCardsEvent(String gameId, String storyId){
        Game_State_Change__e stateChangeEvent = new Game_State_Change__e();
        stateChangeEvent.GameID__c = gameId;
        stateChangeEvent.Type__c = 'ResetCards';
        stateChangeEvent.Data__c = storyId;
        Eventbus.publish(stateChangeEvent);
    }
}